"""Added is_subscribed to User

Revision ID: 8510f1f72da8
Revises: fc9031cb5e8b
Create Date: 2025-03-05 10:33:13.936829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8510f1f72da8'
down_revision: Union[str, None] = 'fc9031cb5e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_subscribed')
    # ### end Alembic commands ###
