"""Added new models

Revision ID: e23f1f679268
Revises: 8510f1f72da8
Create Date: 2025-03-07 17:22:30.102899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23f1f679268'
down_revision: Union[str, None] = '8510f1f72da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_pdf_countries_id'), 'pdf_countries', ['id'], unique=False)
    op.create_table('pdf_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('template_fields', sa.Text(), nullable=True, comment='JSON с описанием полей шаблона'),
    sa.ForeignKeyConstraint(['country_id'], ['pdf_countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_services_id'), 'pdf_services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_services_id'), table_name='pdf_services')
    op.drop_table('pdf_services')
    op.drop_index(op.f('ix_pdf_countries_id'), table_name='pdf_countries')
    op.drop_table('pdf_countries')
    # ### end Alembic commands ###
